"""
Documentation - Constitutional Helper
"""
import streamlit as st

st.set_page_config(page_title="Documentation — Constitutional Helper", page_icon="favicon.png", layout="wide")

# Load shared CSS
import os
css_file = os.path.join(os.path.dirname(__file__), "..", "styles.css")
if os.path.exists(css_file):
    with open(css_file, "r", encoding="utf-8") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

st.markdown("""
<div class="page-container">

<a href="/" target="_self" class="back-link">← Back to Constitutional Helper</a>

# Documentation

## Overview

**Constitutional Helper** is an AI-powered legal assistant designed to make Ghana's 1992 Constitution 
accessible to every citizen. It uses advanced semantic search (RAG) combined with large language models 
to provide accurate, cited answers to constitutional questions.

---

## How It Works

### 1. Ask a Question
Type any question about Ghana's Constitution in the chat input. Questions can be in **English** or **Asante Twi**.

**Example questions:**
- *"What are my rights if I get arrested?"*
- *"How is the President of Ghana elected?"*
- *"What does the Constitution say about freedom of speech?"*

### 2. AI-Powered Search
Your question is processed through a **Retrieval-Augmented Generation (RAG)** pipeline:
1. Your question is converted into a semantic embedding
2. The system searches across all articles of the 1992 Constitution
3. The most relevant constitutional provisions are retrieved
4. An AI model generates a clear, human-readable answer grounded in the actual text

### 3. Get Cited Answers
Every answer includes:
- A **plain-language explanation** written for everyday citizens
- **Article badges** showing which constitutional provisions were referenced
- A **References section** with verbatim quotes from the Constitution

---

## Features

| Feature | Description |
|---|---|
| **Bilingual Support** | Switch between English and Asante Twi |
| **Quick Topics** | Pre-built questions for common constitutional queries |
| **Article Citations** | Every answer references specific constitutional articles |
| **Audio Output** | Listen to answers read aloud (when enabled) |
| **Semantic Search** | AI understands meaning, not just keywords |

---

## Technical Details

- **LLM Provider:** Groq API (Llama 3.3 70B)
- **Embedding Model:** all-MiniLM-L6-v2
- **Framework:** Streamlit
- **Source Document:** 1992 Constitution of the Republic of Ghana

---

## Limitations

- Answers are generated by AI and should not be considered legal advice
- The system is trained on the 1992 Constitution text and may not reflect subsequent amendments
- For complex legal matters, always consult a qualified legal professional

---

## Contact

For questions, feedback, or contributions, reach out to the **GhanaLex Team**.

</div>
""")

# Footer
st.markdown("""
<div class="app-footer">
  <div>
    <a href="/Documentation" target="_self">Documentation</a>
    <a href="/Privacy_Policy" target="_self">Privacy Policy</a>
    <a href="/Terms_of_Service" target="_self">Terms of Service</a>
  </div>
  <div class="footer-brand">© 2026 Constitutional Helper</div>
  <div>Powered by GhanaLex AI • 1992 Constitution of Ghana</div>
</div>
""", unsafe_allow_html=True)
