"""
Terms of Service - Constitutional Helper
"""
import streamlit as st

st.set_page_config(page_title="Terms of Service — Constitutional Helper", page_icon="favicon.png", layout="wide")

# Load shared CSS
import os
css_file = os.path.join(os.path.dirname(__file__), "..", "styles.css")
if os.path.exists(css_file):
    with open(css_file, "r", encoding="utf-8") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

st.markdown("""
<div class="page-container">

<a href="/" target="_self" class="back-link">← Back to Constitutional Helper</a>

# Terms of Service

**Effective Date:** January 1, 2026  
**Last Updated:** April 23, 2026

---

## 1. Acceptance of Terms

By accessing or using Constitutional Helper ("the Service"), you agree to be bound by these 
Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.

---

## 2. Description of Service

Constitutional Helper is a free, AI-powered educational tool that provides information about 
Ghana's 1992 Constitution. The Service uses artificial intelligence to generate plain-language 
explanations of constitutional provisions in response to user questions.

---

## 3. Important Disclaimers

### 3.1 Not Legal Advice
**The Service does not provide legal advice.** All information generated by the Service is for 
educational and informational purposes only. The responses are AI-generated interpretations and 
should not be relied upon as a substitute for professional legal counsel.

### 3.2 No Attorney-Client Relationship
Use of the Service does not create an attorney-client relationship between you and the GhanaLex 
Team or any of its members.

### 3.3 Accuracy
While we strive for accuracy, AI-generated responses may contain errors, omissions, or 
misinterpretations of constitutional text. We make no warranties regarding the completeness, 
reliability, or accuracy of any information provided by the Service.

### 3.4 Constitutional Amendments
The Service is based on the 1992 Constitution of the Republic of Ghana. It may not reflect 
subsequent amendments, judicial interpretations, or legislative changes.

---

## 4. Acceptable Use

You agree to use the Service only for lawful purposes. You shall not:
- Attempt to manipulate, hack, or exploit the AI system
- Use the Service to generate misleading legal claims
- Submit content that is abusive, threatening, or illegal
- Attempt to reverse-engineer, decompile, or extract the underlying models
- Use automated scripts or bots to access the Service at scale
- Misrepresent AI-generated responses as official legal opinions

---

## 5. Intellectual Property

### 5.1 Constitutional Text
The 1992 Constitution of the Republic of Ghana is a public document. Constitutional text 
referenced by the Service is not owned by the GhanaLex Team.

### 5.2 Service Content
The AI-generated explanations, user interface design, branding, and underlying technology 
are the intellectual property of the GhanaLex Team and are protected by applicable laws.

### 5.3 User Content
You retain ownership of the questions you submit. By using the Service, you grant us a 
non-exclusive, royalty-free license to process your questions solely for the purpose of 
generating responses.

---

## 6. Limitation of Liability

To the maximum extent permitted by law:
- The Service is provided "AS IS" without warranties of any kind
- The GhanaLex Team shall not be liable for any direct, indirect, incidental, or 
  consequential damages arising from your use of the Service
- We are not responsible for decisions made based on information provided by the Service
- Total liability shall not exceed zero (0) Ghana Cedis, as the Service is provided free of charge

---

## 7. Service Availability

We reserve the right to:
- Modify, suspend, or discontinue the Service at any time without notice
- Limit access to certain features or functionality
- Implement usage limits to ensure fair access for all users

---

## 8. Indemnification

You agree to indemnify and hold harmless the GhanaLex Team from any claims, damages, or 
expenses arising from your use of the Service or violation of these Terms.

---

## 9. Governing Law

These Terms shall be governed by and construed in accordance with the laws of the Republic 
of Ghana. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction 
of the courts of Ghana.

---

## 10. Changes to Terms

We reserve the right to modify these Terms at any time. Changes will be effective immediately 
upon posting. Your continued use of the Service after changes constitutes acceptance of the 
modified Terms.

---

## 11. Severability

If any provision of these Terms is found to be unenforceable, the remaining provisions shall 
remain in full force and effect.

---

## 12. Contact

For questions about these Terms, contact the **GhanaLex Team**.

</div>
""")

# Footer
st.markdown("""
<div class="app-footer">
  <div>
    <a href="/Documentation" target="_self">Documentation</a>
    <a href="/Privacy_Policy" target="_self">Privacy Policy</a>
    <a href="/Terms_of_Service" target="_self">Terms of Service</a>
  </div>
  <div class="footer-brand">© 2026 Constitutional Helper</div>
  <div>Powered by GhanaLex AI • 1992 Constitution of Ghana</div>
</div>
""", unsafe_allow_html=True)
